#pipeline for admin-panel
# To react files
definitions:
  caches:
    node: node_modules
  steps:
    - step: &install
        name: Install-dependencies
        caches:
          - node
        script:
          - npm install

    - step: &build
        name: Building-app
        caches:
          - node
        script:
          - npm run build
        artifacts:
          - build/**

    - step: &deploy
        name: Deploy-to-S3
        script:
          - pipe: atlassian/aws-s3-deploy:2.0.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: "$BUCKET_NAME"
              LOCAL_PATH: "build"

    - step: &icc
        name: Invalidate Cloudfront Cache
        script:
          - pipe: atlassian/aws-cloudfront-invalidate:0.11.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID

image: node:21

pipelines:
  branches:
    main:
      - stage: 
          name: Build and deploy Production
          deployment: Production
          steps:
            - step: *install
            - step: *build
            - step: *deploy
            - step: *icc

    staging:
      - stage:
          name: Build and deploy Staging
          deployment: Staging
          steps: 
            - step: *install
            - step: *build
            - step: *deploy
            - step: *icc

    develop:
      - stage:
          name: Build and deploy Development
          deployment: Development
          steps:
            - step: *install
            - step: *build
            - step: *deploy
            - step: *icc
